server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5000/usrdb
    username: ralink
    password: ralink

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/