server:
  port: 8080
zuul:
  prefix: /api
  routes:
    user_app:
      path: /user/**
      serviceId: user_app
      strip-prefix: false

eureka:
  client:
    registerWithEureka: false
security:
  jwt:
    expirationTime: 8640000000
    secretKey: sflkj12p4asdifasdfsdfsadfsadfsadfqwer123412