server:
  port: 8080
zuul:
  prefix: /api
  routes:
    user_app:
      path: /user/register**
      serviceId: user_app

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/